openapi: '3.0.2'
info:
  description: "API to get contribution statistics and pinned projects"
  version: "1.0.0"
  title: "Github Statistics API"
  contact:
    name: Thanh Vu
    url: https://github.com/misa198/github-statistic-api
servers:
  - url: https://github-statistic-api-misa198.herokuapp.com
paths:
  /contributions:
    get:
      parameters:
        - name: username
          in: query
          description: "Github username"
          required: true
          schema:
            type: string
        - name: year
          in: query
          description: "Year to get statistics"
          required: false
          schema:
            type: number
            format: int
        - name: allYears
          in: query
          description: "Option to get statistics of all years or not"
          required: false
          schema:
            type: boolean
        - name: format
          in: query
          description: "Return data type. Only available when there is a field 'AllYears'"
          required: false
          schema:
            type: string
            enum:
              - "array"
              - "object"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/GetAllYearsArrayContributionsResponse"
                  - $ref: "#/components/schemas/GetAllYearsObjectContributionsResponse"
        '400':
          description: "Bad request"

  /contributions/years:
    get:
      parameters:
        - name: username
          in: query
          description: "Github username"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetYearsResponse"
        '400':
          description: "Bad request"

  /pinned-projects:
    get:
      parameters:
        - name: username
          in: query
          description: "Github username"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPinnedProjectsResponse"
        '400':
          description: "Bad request"
components:
  schemas:
    Year:
      type: "object"
      properties:
        url:
          type: "string"
        year:
          type: "number"
    Contribution:
      type: "object"
      properties:
        date:
          type: "string"
          format: "string"
        value:
          type: "integer"
          format: "int"
    PinnedProject:
      type: "object"
      properties:
        url:
          type: "string"
        owner:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        stars:
          type: "string"
        forks:
          type: "string"
        language:
          type: "string"
        color:
          type: "string"
    GetAllYearsArrayContributionsResponse:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/Contribution"
    GetAllYearsObjectContributionsResponse:
      type: "object"
      properties:
        data:
          type: "object"
          properties:
            year:
              $ref: "#/components/schemas/Contribution"
    GetYearsResponse:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/Year"
    GetPinnedProjectsResponse:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/PinnedProject"

